import os
from dotenv import load_dotenv

load_dotenv()

#DO NOT CHANGE THE VARIABLE NAME TOKEN, IT IS USED IN THE MAIN.PY FILE TO RUN THE BOT
#IF YOU DO NOT KNOW HOW TO USE THE .ENV FILE, PLEASE ASK FOR HELP IN THE SUPPORT SERVER
# DO NOT MESS WITH THE .ENV FILE, IT IS USED TO STORE SENSITIVE INFORMATION SUCH AS THE BOT TOKEN




# Load the bot token from the .env file
TOKEN= os.getenv('DISCORD_TOKEN')